import Head from 'next/head'

const Header = ({ memeSelected = 0 }) => {
    return <Head>
    <title>ESPE DEMO - {memeSelected}</title>
    <meta name="description" content="Generated by create next app" />
    <link rel="icon" href="/favicon.ico" />
  </Head>
}


export default Header;